### ISSUE TITLE
Plugin 'DBT' (version '0.2.5') is not compatible with the current version of the IDE

### ISSUE THREAD

**Issue by tim-watcha** [rinchinov/ij-dbt-plugin#104]
**Describe the bug**
Plugin 'DBT' (version '0.2.5') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is PY-242.20224.428

**To Reproduce**
I cannot install with newest version of pycharm.

This is my detailed version:
PyCharm 2024.2.0.1 (Professional Edition)
Build #PY-242.20224.428, built on August 21, 2024
Licensed to Choongjae Lee
Subscription is active until July 27, 2025.
Runtime version: 21.0.3+13-b509.4 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 20
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.ml.llm (242.20224.424)
  net.chakmidlot.jetbrains.bigquery.plugin (0.1.3)
  com.jetbrains.space (242.20224.155)
  com.github.continuedev.continueintellijextension (0.0.62)
  com.github.ramonvermeulen.dbtToolkit (0.1.0)
  com.koxudaxi.ruff (0.0.35)
  ee.carlrobert.chatgpt (2.10.1-241.1)
  com.intellij.bigdatatools.core (242.20224.419)
  com.intellij.bigdatatools.binary.files (242.20224.159)
  com.intellij.bigdatatools.rfs (242.20224.419)
  com.github.copilot (1.5.20.6554)

**Expected behavior**
Installed properly

**Screenshots**
<img width="436" alt="스크린샷 2024-08-23 오후 5 19 43" src="https://github.com/user-attachments/assets/aecec829-b496-4ad7-b013-5a93b1fd9df2">

**Details**
 - OS: Mac OS Sonoma 14.6.1(23G93)

**Comment by marlic7** [comment]
On Ubuntu there is exception in plugin DBT (0.2.5):

```
java.lang.NoClassDefFoundError: com/intellij/jinja/psi/Jinja2StringLiteral
	at com.github.rinchinov.ijdbtplugin.annotations.ModelAnnotations.annotate(ModelAnnotations.kt:23)
	at com.intellij.codeInsight.daemon.impl.AnnotationHolderImpl.runAnnotatorWithContext(AnnotationHolderImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotator$2(AnnotatorRunner.java:130)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotator(AnnotatorRunner.java:120)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$0(AnnotatorRunner.java:67)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:333)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.lambda$runAnnotatorsAsync$1(AnnotatorRunner.java:67)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:126)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:207)
	at com.intellij.concurrency.ApplierCompleter.helpOthers(ApplierCompleter.java:227)
	at com.intellij.concurrency.ApplierCompleter.helpAll(ApplierCompleter.java:186)
	at com.intellij.concurrency.ApplierCompleter.lambda$exec$0(ApplierCompleter.java:116)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:158)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:169)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapAndRun$1(ApplierCompleter.java:150)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:544)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:176)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:150)
	at com.intellij.concurrency.ApplierCompleter.exec(ApplierCompleter.java:118)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.ClassNotFoundException: com.intellij.jinja.psi.Jinja2StringLiteral PluginClassLoader(plugin=PluginDescriptor(name=DBT, id=com.github.rinchinov.ijdbtplugin, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/ij-dbt-plugin, version=0.2.5, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.terminal, descriptorPath=intellij.python.terminal.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.terminal, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.markdown, descriptorPath=intellij.python.markdown.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.markdown, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.langInjection, descriptorPath=intellij.python.langInjection.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.langInjection, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.grazie, descriptorPath=intellij.python.grazie.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.grazie, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.featuresTrainer, descriptorPath=intellij.python.featuresTrainer.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.featuresTrainer, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.copyright, descriptorPath=intellij.python.copyright.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.copyright, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minorRider, descriptorPath=intellij.python.community.plugin.minorRider.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.community.plugin.minorRider, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minor, descriptorPath=intellij.python.community.plugin.minor.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.community.plugin.minor, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.java, descriptorPath=intellij.python.community.plugin.java.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.community.plugin.java, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.impl, descriptorPath=intellij.python.community.plugin.impl.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.community.plugin.impl, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.impl.huggingFace, descriptorPath=intellij.python.community.impl.huggingFace.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.community.impl.huggingFace, isBundled=false), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.communityOnly, descriptorPath=intellij.python.community.communityOnly.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.python.community.communityOnly, isBundled=false), PluginDescriptor(name=Database Tools and SQL, id=com.intellij.database, moduleName=intellij.database.grazie, descriptorPath=intellij.database.grazie.xml, path=/opt/idea-IU-241.18034.62/plugins/DatabaseTools, version=243.22562.145, package=com.intellij.database.grazie, isBundled=true), PluginDescriptor(name=Database Tools and SQL, id=com.intellij.database, moduleName=intellij.database.flameGraphs, descriptorPath=intellij.database.flameGraphs.xml, path=/opt/idea-IU-241.18034.62/plugins/DatabaseTools, version=243.22562.145, package=com.intellij.database.flameGraph, isBundled=true), PluginDescriptor(name=Database Tools and SQL, id=com.intellij.database, moduleName=intellij.database.docker, descriptorPath=intellij.database.docker.xml, path=/opt/idea-IU-241.18034.62/plugins/DatabaseTools, version=243.22562.145, package=com.intellij.database.docker, isBundled=true), PluginDescriptor(name=Database Tools and SQL, id=com.intellij.database, moduleName=intellij.modules.database/dialects.oracle.utplsql.coverage, descriptorPath=intellij.modules.database.dialects.oracle.utplsql.coverage.xml, path=/opt/idea-IU-241.18034.62/plugins/DatabaseTools, version=243.22562.145, package=com.intellij.database.dialects.oracle.testing.utplsql.coverage, isBundled=true), PluginDescriptor(name=Database Tools and SQL, id=com.intellij.database, moduleName=intellij.database.diagrams, descriptorPath=intellij.database.diagrams.xml, path=/opt/idea-IU-241.18034.62/plugins/DatabaseTools, version=243.22562.145, package=com.intellij.database.diagram, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.commandInterface, descriptorPath=intellij.commandInterface.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.intellij.commandInterface, isBundled=false), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=/opt/idea-IU-241.18034.62/lib, version=243.22562.145, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=/opt/idea-IU-241.18034.62/lib, version=243.22562.145, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=/opt/idea-IU-241.18034.62/lib, version=243.22562.145, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=/opt/idea-IU-241.18034.62/lib, version=243.22562.145, package=null, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2024.3/python-ce, version=243.22562.145, package=com.jetbrains.python, isBundled=false), PluginDescriptor(name=Database Tools and SQL, id=com.intellij.database, descriptorPath=plugin.xml, path=/opt/idea-IU-241.18034.62/plugins/DatabaseTools, version=243.22562.145, package=null, isBundled=true), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:157)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 33 more

```
